version: '2'
services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    labels:
      service.name: "node-exporter"
      service.group: "monitoring"
      service.project: "my_project"
      service.environment: "production"
